---
name: "Apple Music"
guid: "a9f62a44-fea5-46c3-ac26-55abba29c7c8"
version: "3.0.5.1"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Fetch images and metadata from Apple Music."
description: >
  Apple Music artist and album images and metadata provider.
category: "Metadata"
owner: "lyarenei"
artifacts:
- "AngleSharp.dll"
- "AngleSharp.XPath.dll"
- "Jellyfin.Plugin.AppleMusic.dll"
changelog: >
  Fix:
    - Album artwork being pulled if artist did not have one
